from pydantic import BaseModel, EmailStr, constr, Field
from datetime import datetime
from typing import Optional
from Enum import StatusEnum


class PropertyData(BaseModel):
    FIPSCode: str
    PropertyFullStreetAddress: str
    PropertyCityName: str
    PropertyState: str
    PropertyZipCode: str
    PropertyZip4: str
    PropertyUnitType: str
    PropertyUnitNumber: str
    PropertyHouseNumber: str
    PropertyStreetDirectionLeft: str
    PropertyStreetName: str
    PropertyStreetSuffix: str
    PropertyStreetDirectionRight: str
    PropertyAddressCarrierRoute: str
    RecordType: str
    RecordingDate: str
    RecorderBookNumber: str
    RecorderPageNumber: str
    RecorderDocumentNumber: str
    APN: str
    MultiAPNFlag: str
    Borrower1FirstNameMiddleName: str
    Borrower1LastNameOeCorporationName: str
    Borrower1IDCode: str
    Borrower2FirstNameMiddleName: str
    Borrower2LastNameOrCorporationName: str
    Borrower2IDCode: str
    BorrowerVestingCode: str
    LegalLotNumbers: str
    LegalBlock: str
    LegalSection: str
    LegalDistrict: str
    LegalLandLot: str
    LegalUnit: str
    LegalCityTownshipMunicipality: str
    LegalSubdivisionName: str
    LegalPhaseNumber: str
    LegalTractNumber: str
    LegalBriefDescription: str
    LegalSectionTownshipRangeMeridian: str
    LenderNameBeneficiary: str
    LenderNameID: str
    LenderType: str
    LoanAmount: int
    LoanType: str
    TypeFinancing: str
    InterestRate: float
    DueDate: str
    AdjustableRateRider: str
    AdjustableRateIndex: str
    ChangeIndex: float
    RateChangeFrequency: str
    InterestRateNotGreaterThan: float
    InterestRateNotLessThan: float
    MaximumInterestRate: float
    InterestOnlyPeriod: str
    FixedStepConversionRateRider: str
    FirstChangeDateYearConversionRider: str
    FirstChangeDateMonthDayConversionRider: str
    PrepaymentRider: str
    PrepaymentTermPenaltyRider: str
    BuyerMailFullStreetAddress: str
    BorrowerMailUnitType: str
    BorrowerMailUnitNumber: str
    BorrowerMailCity: str
    BorrowerMailState: str
    BorrowerMailZipCode: str
    BorrowerMailZip4: str
    OriginalDateOfContract: str
    TitleCompanyName: str
    LenderDBAName: str
    LenderMailFullStreetAddress: str
    LenderMailUnitType: str
    LenderMailUnit: str
    LenderMailCity: Optional[str] = ""
    LenderMailState: str
    LenderMailZipCode: str
    LenderMailZip4: str
    LoanTermMonths: str
    LoanTermYears: str
    LoanNumber: str
    PID: int
    AssessorLandUse: str
    ResidentialIndicator: bool
    ConstructionLoan: bool
    CashPurchase: bool
    StandAloneRefi: bool
    EquityCreditLine: bool
    PropertyUseCode: str
    LoanTransactionType: str
    MainRecordIDCode: str
    LoanOrganizationNMLS_ID: str
    LoanOrganizationName: str
    MortgageBrokerNMLS_ID: str
    MortgageBroker: str
    LoanOfficerNMLS_ID: str
    LoanOfficerName: str
    DPID: str
    UpdateTimeStamp: str
